title: jameskeal.com.au
description: "James Keal"
url: "https://jameskeal.com.au"
baseurl: "/"

favicon: yes
favicon_dir: "/img/favicon"

author: James Keal
profile_picture: "https://avatars2.githubusercontent.com/u/2309403"
twitter_username: "_keeeal"

markdown: kramdown
highlighter: rouge
permalink: /:title

footer: yes
footer_url: "https://github.com/keeeal"
footer_text: "Find me on Github"

sass:
  style: compressed
  sass_dir: _sass

nav:
 - name: "About Me"
   link: "/about"

plugins:
  - jekyll-feed