title: jameskeal.com.au
description: "James Keal"
url: "https://jameskeal.com.au"
baseurl: "/"

author: James Keal
profile_picture: "https://avatars2.githubusercontent.com/u/2309403"
twitter_username: "_keeeal"

markdown: kramdown
highlighter: rouge

footer: yes
footer_url: "https://github.com/keeeal"
footer_text: "Find me on Github"

sass:
  style: compressed
  sass_dir: _sass

nav:
 - name: "Projects"
   link: "/projects"
 - name: "About Me"
   link: "/about"
 - name: "Contact"
   link: "/about#email"
