title: James Keal
url: "https://jameskeal.com.au"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/keeeal"
footer_text: "Find me on Github"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"
 - name: "Contact"
   link: "contact"
